### ISSUE TITLE
I can't install the environment to reproduce the results

### ISSUE THREAD

**Issue by wyh196646** [csh3/stFormer#1]
can you supply the package version in your conda environment, especially "flash_attn"? Really appreciates!

**Comment by csh3** [comment]
I have added a configuration file and now you can install the package along with all dependencies  using one command "pip install -e .". For the detailed installation guidelines, please see the updated README. Thanks for your suggestions.

**Comment by sowhat0001** [comment]
Hi, could you tell me what version of cell2location you're using? I don't see it in the toml file.

**Comment by csh3** [comment]
The version of cell2location used here is 0.1.3.
